set-window-option -g mode-keys vi
set -sg escape-time 0
set-option -ga terminal-overrides ',xterm-256color:Tc'
set -g default-terminal "tmux-256color"
set -g focus-events on

# open new panes in cwd
bind '"' split-window -c "#{pane_current_path}"
bind '%' split-window -h -c "#{pane_current_path}"

# navigate among panes with vim key bindings
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# long history
set-option -g history-limit 50000

# Smart pane switching with awareness of Vim splits.
bind-key -n 'C-h' if-shell '~/Code/dotfiles/is_vim.sh' 'send-keys C-h' 'select-pane -L'
bind-key -n 'C-j' if-shell '~/Code/dotfiles/is_vim.sh' 'send-keys C-j' 'select-pane -D'
bind-key -n 'C-k' if-shell '~/Code/dotfiles/is_vim.sh' 'send-keys C-k' 'select-pane -U'
bind-key -n 'C-l' if-shell '~/Code/dotfiles/is_vim.sh' 'send-keys C-l' 'select-pane -R'

bind-key -T copy-mode-vi 'C-h' select-pane -L
bind-key -T copy-mode-vi 'C-j' select-pane -D
bind-key -T copy-mode-vi 'C-k' select-pane -U
bind-key -T copy-mode-vi 'C-l' select-pane -R
